blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Home:index }

blog_add_post:
    path:     /post/add
    defaults: { _controller: BlogBundle:Post:add }

blog_posts:
    path:   /posts
    defaults: { _controller: BlogBundle:Post:index}

blog_show_post:
    path:   /post/{id}
    defaults: { _controller: BlogBundle:Post:show}
    requirements:
        id: \d+
blog_update_post:
    path:   /post/update/{id}
    defaults: { _controller: BlogBundle:Post:update}
    requirements:
        id: \d+



blog_page:
    path:    /page/{page}
    defaults: { _controller: BlogBundle:Home:page}
    requirements:
        page: \d+

# blog_article:
#     path:     /article/{_locale}/{annee}/{slug}.{_format}
#     defaults: { _controller:BlogBundle:Home:article, _format: html, _locale: fr }
#     requirements:
#         annee: \d{4}
#         _format: rss|html
#         _locale: fr|en

blog_article:
    path:     /article/{slug}
    defaults: { _controller:BlogBundle:Home:article, _format: html, _locale: fr }
